import 'package:flutter/material.dart';

const TextTheme whiteCupertino = TextTheme(
  displayLarge: TextStyle(
    debugLabel: 'whiteCupertino displayLarge',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.white70,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  displayMedium: TextStyle(
    debugLabel: 'whiteCupertino displayMedium',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.white70,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  displaySmall: TextStyle(
    debugLabel: 'whiteCupertino displaySmall',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.white70,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  headlineLarge: TextStyle(
    debugLabel: 'whiteCupertino headlineLarge',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.white70,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  headlineMedium: TextStyle(
    debugLabel: 'whiteCupertino headlineMedium',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.white70,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  headlineSmall: TextStyle(
    debugLabel: 'whiteCupertino headlineSmall',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  titleLarge: TextStyle(
    debugLabel: 'whiteCupertino titleLarge',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  titleMedium: TextStyle(
    debugLabel: 'whiteCupertino titleMedium',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  titleSmall: TextStyle(
    debugLabel: 'whiteCupertino titleSmall',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  bodyLarge: TextStyle(
    debugLabel: 'whiteCupertino bodyLarge',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  bodyMedium: TextStyle(
    debugLabel: 'whiteCupertino bodyMedium',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  bodySmall: TextStyle(
    debugLabel: 'whiteCupertino bodySmall',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white70,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  labelLarge: TextStyle(
    debugLabel: 'whiteCupertino labelLarge',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  labelMedium: TextStyle(
    debugLabel: 'whiteCupertino labelMedium',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  labelSmall: TextStyle(
    debugLabel: 'whiteCupertino labelSmall',
    fontFamily: 'CupertinoSystemText',
    color: Colors.white,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
);

const TextTheme blackCupertino = TextTheme(
  displayLarge: TextStyle(
    debugLabel: 'blackCupertino displayLarge',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.black54,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  displayMedium: TextStyle(
    debugLabel: 'blackCupertino displayMedium',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.black54,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  displaySmall: TextStyle(
    debugLabel: 'blackCupertino displaySmall',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.black54,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  headlineLarge: TextStyle(
    debugLabel: 'blackCupertino headlineLarge',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.black54,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  headlineMedium: TextStyle(
    debugLabel: 'blackCupertino headlineMedium',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.black54,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  headlineSmall: TextStyle(
    debugLabel: 'blackCupertino headlineSmall',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  titleLarge: TextStyle(
    debugLabel: 'blackCupertino titleLarge',
    fontFamily: 'CupertinoSystemDisplay',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  titleMedium: TextStyle(
    debugLabel: 'blackCupertino titleMedium',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  titleSmall: TextStyle(
    debugLabel: 'blackCupertino titleSmall',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  bodyLarge: TextStyle(
    debugLabel: 'blackCupertino bodyLarge',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  bodyMedium: TextStyle(
    debugLabel: 'blackCupertino bodyMedium2',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  bodySmall: TextStyle(
    debugLabel: 'blackCupertino bodySmall',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  labelLarge: TextStyle(
    debugLabel: 'blackCupertino labelLarge2',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black87,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  labelMedium: TextStyle(
    debugLabel: 'blackCupertino labelMedium',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black26,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
  labelSmall: TextStyle(
    debugLabel: 'blackCupertino labelSmall',
    fontFamily: 'CupertinoSystemText',
    color: Colors.black26,
    decoration: TextDecoration.none,
    fontFamilyFallback: ["PingFang SC"],
  ),
);

const TextTheme englishLike = TextTheme(
  displayLarge: TextStyle(
    debugLabel: 'englishLike displayLarge 2021',
    inherit: false,
    fontSize: 57.0,
    fontWeight: FontWeight.w400,
    letterSpacing: -0.25,
    height: 1.12,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  displayMedium: TextStyle(
    debugLabel: 'englishLike displayMedium 2021',
    inherit: false,
    fontSize: 45.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.16,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  displaySmall: TextStyle(
    debugLabel: 'englishLike displaySmall 2021',
    inherit: false,
    fontSize: 36.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.22,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  headlineLarge: TextStyle(
    debugLabel: 'englishLike headlineLarge 2021',
    inherit: false,
    fontSize: 32.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.25,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  headlineMedium: TextStyle(
    debugLabel: 'englishLike headlineMedium 2021',
    inherit: false,
    fontSize: 28.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.29,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  headlineSmall: TextStyle(
    debugLabel: 'englishLike headlineSmall 2021',
    inherit: false,
    fontSize: 24.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  titleLarge: TextStyle(
    debugLabel: 'englishLike titleLarge 2021',
    inherit: false,
    fontSize: 22.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.0,
    height: 1.27,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  titleMedium: TextStyle(
    debugLabel: 'englishLike titleMedium 2021',
    inherit: false,
    fontSize: 16.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.15,
    height: 1.50,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  titleSmall: TextStyle(
    debugLabel: 'englishLike titleSmall 2021',
    inherit: false,
    fontSize: 14.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  labelLarge: TextStyle(
    debugLabel: 'englishLike labelLarge 2021',
    inherit: false,
    fontSize: 14.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.1,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  labelMedium: TextStyle(
    debugLabel: 'englishLike labelMedium 2021',
    inherit: false,
    fontSize: 12.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  labelSmall: TextStyle(
    debugLabel: 'englishLike labelSmall 2021',
    inherit: false,
    fontSize: 11.0,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.5,
    height: 1.45,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  bodyLarge: TextStyle(
    debugLabel: 'englishLike bodyLarge 2021',
    inherit: false,
    fontSize: 16.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.5,
    height: 1.50,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  bodyMedium: TextStyle(
    debugLabel: 'englishLike bodyMedium 20212',
    inherit: false,
    fontSize: 14.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.25,
    height: 1.43,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
  bodySmall: TextStyle(
    debugLabel: 'englishLike bodySmall 2021',
    inherit: false,
    fontSize: 12.0,
    fontWeight: FontWeight.w400,
    letterSpacing: 0.4,
    height: 1.33,
    textBaseline: TextBaseline.alphabetic,
    leadingDistribution: TextLeadingDistribution.even,
  ),
);

const TextTheme dense = TextTheme(
  displayLarge: TextStyle(
    debugLabel: 'dense displayLarge 2018',
    inherit: false,
    fontSize: 96.0,
    fontWeight: FontWeight.w100,
    textBaseline: TextBaseline.ideographic,
  ),
  displayMedium: TextStyle(
    debugLabel: 'dense displayMedium 2018',
    inherit: false,
    fontSize: 60.0,
    fontWeight: FontWeight.w100,
    textBaseline: TextBaseline.ideographic,
  ),
  displaySmall: TextStyle(
    debugLabel: 'dense displaySmall 2018',
    inherit: false,
    fontSize: 48.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  headlineLarge: TextStyle(
    debugLabel: 'dense headlineLarge 2018',
    inherit: false,
    fontSize: 40.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  headlineMedium: TextStyle(
    debugLabel: 'dense headlineMedium 2018',
    inherit: false,
    fontSize: 34.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  headlineSmall: TextStyle(
    debugLabel: 'dense headlineSmall 2018',
    inherit: false,
    fontSize: 24.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  titleLarge: TextStyle(
    debugLabel: 'dense titleLarge 2018',
    inherit: false,
    fontSize: 21.0,
    fontWeight: FontWeight.w500,
    textBaseline: TextBaseline.ideographic,
  ),
  titleMedium: TextStyle(
    debugLabel: 'dense titleMedium 2018',
    inherit: false,
    fontSize: 17.0,
    fontWeight: FontWeight.w500,
    textBaseline: TextBaseline.ideographic,
  ),
  titleSmall: TextStyle(
    debugLabel: 'dense titleSmall 2018',
    inherit: false,
    fontSize: 15.0,
    fontWeight: FontWeight.w500,
    textBaseline: TextBaseline.ideographic,
  ),
  bodyLarge: TextStyle(
    debugLabel: 'dense bodyLarge 2018',
    inherit: false,
    fontSize: 17.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  bodyMedium: TextStyle(
    debugLabel: 'dense bodyMedium 2018',
    inherit: false,
    fontSize: 15,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  bodySmall: TextStyle(
    debugLabel: 'dense bodySmall 2018',
    inherit: false,
    fontSize: 14.0,
    fontWeight: FontWeight.w400,
    textBaseline: TextBaseline.ideographic,
  ),
  labelLarge: TextStyle(
    debugLabel: 'dense labelLarge 2018',
    inherit: false,
    fontSize: 13.0,
    fontWeight: FontWeight.w500,
    textBaseline: TextBaseline.ideographic,
  ),
  labelMedium: TextStyle(
    debugLabel: 'dense labelMedium 2018',
    inherit: false,
    fontSize: 12.0,
    fontWeight: FontWeight.w500,
    textBaseline: TextBaseline.ideographic,
  ),
  labelSmall: TextStyle(
    debugLabel: 'dense labelSmall 2018',
    inherit: false,
    fontSize: 11.0,
    fontWeight: FontWeight.w500,
    textBaseline: TextBaseline.ideographic,
  ),
);
